name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build -t ownya23/testimg:latest .
    - name: Run Docker container
      run: docker run -d --name testimg-container -p 8080:8080 ownya23/testimg:latest
