name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t testimg.tar .
    - name: Run Docker container
      run: docker run -d --name myapp-container -p 8080:8080 testimg.tar
